

title: Shepherd
email: your-email@example.com

#highlighter: rouge
#markdown: kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge

# Build settings
#theme: minima

#每页大小
paginate: 5
#jekyll插件
plugins:
  - jekyll-feed
  - jekyll-paginate
